from app.schemas.analysis import AnalyzeTextResponse


def analyze_letter_text(letter_text: str) -> AnalyzeTextResponse:
    return AnalyzeTextResponse(
        sender="Not clearly identified in this test response.",
        letter_topic="Test letter analysis",
        summary="This is a temporary summary for testing the analysis endpoint.",
        important_information=[
            "This is temporary important information for testing."
        ],
        deadlines=[],
        required_actions=[
            "This is a temporary required action."
        ],
        payment_information=[],
        unclear_or_risky_parts=[
            "This is a temporary unclear or risky part."
        ],
        next_steps=[
            "Later, this response will be generated by the LLM."
        ],
        safety_note="This is not legal advice. Please verify important information with the responsible office."
    )